# infra/docker/Dockerfile.frontend

# Stage 1: Build
FROM node:22.16.0-slim AS builder
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --cache /tmp/empty-cache && rm -rf /tmp/empty-cache

COPY . .
RUN npm run build

# Stage 2: Production
FROM nginx:1.27-alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 