# Stage 1: Build
FROM node:22.16.0-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --cache /tmp/empty-cache && rm -rf /tmp/empty-cache
COPY . .
RUN npm run lint

# Stage 2: Production
FROM node:22.16.0-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends tini && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app ./
EXPOSE 5000
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["npm", "start"]